highlight-font: '"GT Walsheim", "gt_walsheim_regular", "Avant Garde Gothic ITCW01Dm", "Avant Garde", "Helvetica Neue", "Arial" '
body: '"Helvetica Neue", "Arial", san-serif'
code: '"Monaco", "Menlo", "Consolas", "Courier New", monospace'

highlight-color: "#19C2A5"
highlight-dark-color: "#16AB91"
darker-color: "#0E705F"
darker-dark-color: "#09453A"
background-color: "#9B9B9B"
alt-link-color: "#B094B7"
warning-color: "#B80E3D"

additional_guides:
    - https://github.com/armadsen/ORSSerialPort/wiki/Installing-ORSSerialPort
    - https://github.com/armadsen/ORSSerialPort/wiki/Getting-Started
    - https://github.com/armadsen/ORSSerialPort/wiki/Packet-Parsing-API
    - https://github.com/armadsen/ORSSerialPort/wiki/Request-Response-API
    - https://github.com/armadsen/ORSSerialPort/wiki/System-Requirements
    - https://github.com/armadsen/ORSSerialPort/wiki/Getting-Vendor-ID-and-Product-ID